#!/bin/bash

echo "Removing old files..."
rm -f "/Library/MobileSubstrate/DynamicLibraries/ TweakExcluder.dylib" "/Library/MobileSubstrate/DynamicLibraries/ TweakExcluder.plist" "/Library/MobileSubstrate/DynamicLibraries/TweakExcluder.dylib" "/Library/MobileSubstrate/DynamicLibraries/TweakExcluder.plist" &> /dev/null
echo "Renaming tweak to make it load before other tweaks..."
mv "/Library/MobileSubstrate/DynamicLibraries/TweakConfigurator.dylib" "/Library/MobileSubstrate/DynamicLibraries/ TweakConfigurator.dylib" &> /dev/null
mv "/Library/MobileSubstrate/DynamicLibraries/TweakConfigurator.plist" "/Library/MobileSubstrate/DynamicLibraries/ TweakConfigurator.plist" &> /dev/null