#!/bin/bash

echo "Removing files..."
rm -f "/Library/MobileSubstrate/DynamicLibraries/TweakConfigurator.dylib" "/Library/MobileSubstrate/DynamicLibraries/TweakConfigurator.plist" &> /dev/null
echo "Moving the tweak back to where it was installed..."
mv "/Library/MobileSubstrate/DynamicLibraries/ TweakConfigurator.dylib" "/Library/MobileSubstrate/DynamicLibraries/TweakConfigurator.dylib" &> /dev/null
mv "/Library/MobileSubstrate/DynamicLibraries/ TweakConfigurator.plist" "/Library/MobileSubstrate/DynamicLibraries/TweakConfigurator.plist" &> /dev/null